[package]
name        = "flix-semver2"
description = "A package handling the semantic versioning v2"
version     = "1.0.0"
flix        = "0.73.0"
license     = "AGPL-3.0-only"
authors     = ["Kengo TODA <skypencil@gmail.com>"]
